<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('users')->insert([
      ['name' => 'Robert De Niro',
        'user_type' => '0',
        'email' => 'robert@example.com',
        'gender' => '0',
        'self_introduction' => 'I am Robert De Niro',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Jack Nicholson',
        'user_type' => '0',
        'email' => 'nicholson@example.com',
        'gender' => '0',
        'self_introduction' => 'I am Jack Nicholson',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Marlon Brando',
        'user_type' => '0',
        'email' => 'marlon@example.com',
        'gender' => '0',
        'self_introduction' => 'I am Marlon Brando',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Katharine Hepburn',
        'user_type' => '0',
        'email' => 'katharine@example.com',
        'gender' => '1',
        'self_introduction' => 'I am Katharine Hepburn',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Tom Hanks',
        'user_type' => '0',
        'email' => 'hanks@example.com',
        'gender' => '0',
        'self_introduction' => 'I am Tom Hanks',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Ariana Grande',
        'user_type' => '0',
        'email' => 'ariana@example.com',
        'gender' => '1',
        'self_introduction' => 'I am Ariana Grande',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Taylor Swift',
        'user_type' => '0',
        'email' => 'taylor@example.com',
        'gender' => '1',
        'self_introduction' => 'I am Taylor Swift',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Lady Gaga',
        'user_type' => '0',
        'email' => 'gaga@example.com',
        'gender' => '1',
        'self_introduction' => 'I am Lady Gaga',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Selena Gomez',
        'user_type' => '0',
        'email' => 'selena@example.com',
        'gender' => '1',
        'self_introduction' => 'I am Selena Gomez',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Ed Sheeran',
        'user_type' => '0',
        'email' => 'sheeran@example.com',
        'gender' => '0',
        'self_introduction' => 'I am Ed Sheeran',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      
      ['name' => 'Google',
        'user_type' => '1',
        'email' => 'company1@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Google',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Apple',
        'user_type' => '1',
        'email' => 'company2@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Apple',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'The Walt Disney Company',
        'user_type' => '1',
        'email' => 'company3@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are The Walt Disney Company',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Amazon',
        'user_type' => '1',
        'email' => 'company4@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Amazon',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Nike',
        'user_type' => '1',
        'email' => 'company5@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Nike',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'J.P. Morgan',
        'user_type' => '1',
        'email' => 'company6@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are J.P. Morgan',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Netflix',
        'user_type' => '1',
        'email' => 'company7@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Netflix',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Tesla',
        'user_type' => '1',
        'email' => 'company8@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Tesla',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Goldman Sachs',
        'user_type' => '1',
        'email' => 'company9@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Goldman Sachs',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
      ['name' => 'Spotify',
        'user_type' => '1',
        'email' => 'company10@example.com',
        'gender' => NULL,
        'self_introduction' => 'We are Spotify',
        'img_name' => NULL,
        'password' => Hash::make('password123'),
      ],
    ]);
  }
}


